### ISSUE TITLE
建议前后端分离

### ISSUE THREAD

**Issue by feilongproject** [paotuan/qqchannel-bot#1]
通过前后端分离，前端可以部署在vercel等静态网页中，防止运行vue导致的性能损耗问题，同时分离后，两个项目会有各自的src文件，不再是一个项目下既有server也有src
（另外类型定义文件可以使用`declare global`作为全局类型定义，不再需要导入）

**Comment by maliut** [comment]
感谢反馈！
其实项目目前已经是前后端分离的了，只是代码都在同一个项目里面。构建的时候都是分开构建的，部署的话只要修改一下前端代码里的服务器地址，就可以像你说的那样单独部署静态网页。

之所以现在的目录看上去很怪异，server 和 src 平级，这个确实不太好，是因为最早是用前端脚手架起的项目，而且后端功能比较简单（要不是 API 限制了纯前端调用，我甚至不想要后端），所以就直接放在一个子文件夹里了。可以当成是一种简陋版的 monorepo 实现吧。如果后面实在是痛，可能会改成比较标准的 monorepo 形式。

代码放同一个仓库的另一个原因是，我觉得大多数目标用户应该是不懂代码的，搞服务器部署的是少数。我希望能直接打个包给普通用户使用，放同一个仓库打包也会比较方便。

**Comment by feilongproject** [comment]
如果想要打包的话，可以做成前端通过设置项与后端通信。目标用户只需要在后端进行部署就可以，前端在自动编译好后就无需用户再进行编译，直接使用现成的网页与服务器通信

**Comment by maliut** [comment]
你指的应该是 在公网上部署一个或几个公共的后端，然后前端部署静态服务，普通用户访问公共的前端网页，可以自主选择想要连接的后端 这种形式吧（希望我没理解错

我期望的打包是，生成一个可执行文件，用户在本地运行，就相当于起了一个本地服务器，连接 localhost
