### ISSUE TITLE
Docker内的错误提示

### ISSUE THREAD

**Issue by RZCN86** [paotuan/qqchannel-bot#11]
黑群晖DS918 Plus
部署环境：docker
错误日志：感觉是在docker环境下仍然试图拉起浏览器。
![image](https://github.com/paotuan/qqchannel-bot/assets/5794646/630f07e8-4bef-4138-9053-f82d334cfead)

**Comment by maliut** [comment]
确实是试图拉起浏览器，不过做了 try catch 处理，应该不会对正常使用产生影响？

**Comment by RZCN86** [comment]
![image](https://github.com/paotuan/qqchannel-bot/assets/5794646/87923ac7-7410-47a6-86ef-c93bcc44ae5c)
一直卡在连接界面上，docker日志上看不到任何提示。只有上面截图的内容……

**Comment by maliut** [comment]
如群内所讨论，可能是防火墙未开放4174（websocket服务端）的端口

如果担心是拉起浏览器的问题，可使用 fix/browser 分支 暂时注释了拉起浏览器的逻辑，可以试下能不能解决问题
