### ISSUE TITLE
希望可以增加更多DND人物卡的导入支持

### ISSUE THREAD

**Issue by GoGoZEPPLI** [paotuan/qqchannel-bot#12]
https://www.goddessfantasy.net/bbs/index.php?topic=144212.0#top
希望增加对上文网页中这个卡的支持 目前无法导入这个卡
因为这个自动卡非常方便，有背包算账等等功能，车新卡很好用
求求力

**Comment by maliut** [comment]
好，我周末的时候康康

**Comment by maliut** [comment]
> https://www.goddessfantasy.net/bbs/index.php?topic=144212.0#top 希望增加对上文网页中这个卡的支持 目前无法导入这个卡 因为这个自动卡非常方便，有背包算账等等功能，车新卡很好用 求求力

https://github.com/paotuan/qqchannel-bot/releases/tag/v1.8.2-alpha

已添加，可以试试
