### ISSUE TITLE
大佬求更新，docker版本的还是1.8

### ISSUE THREAD

**Issue by wenjiavv** [paotuan/qqchannel-bot#15]
大佬求更新，docker版本的还是1.8

**Comment by maliut** [comment]
可以参考文档 https://www.paotuan.io/setup/download/docker.html 自构建镜像

docker hub 上的话，需要 @monthwolf 大佬有空更新下

**Comment by monthwolf** [comment]
ok，已经更新了1.9.0和最新2.0.0-alpha.6的镜像
