### ISSUE TITLE
下载后无法运行程序

### ISSUE THREAD

**Issue by dXXXcris** [paotuan/qqchannel-bot#6]
对话框闪过，无反应
0.3.0版本
win7系统

**Comment by maliut** [comment]
你好，我手上没有 win7 的设备，无法验证具体是什么问题。但我查了下，win7 最新支持的 nodejs 稳定版本是 12.x. 而目前程序是基于 16.x 的版本打包的，因此可能是版本不兼容导致的。

我尝试基于 node12 打包了一个版本，你可以在这里下载：https://github.com/paotuan/qqchannel-bot/releases/tag/v0.3.0-node12  尝试下看看能不能正常使用。

另外还有个可能性是打包程序目前只支持 64 位的系统。如果你的系统是 32 位的，应该也无法正常运行。

**Comment by dXXXcris** [comment]
感谢，64位可以运行

**Comment by maliut** [comment]
太好了！那么后续版本更新我也会把支持 win7 的版本加上，感谢你的支持~
